name: Create Release

on:
  workflow_run:
    workflows: ["Build Android APK"]
    types: [completed]

jobs:
  create-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download APK artifact
      uses: actions/download-artifact@v4
      with:
        name: app-debug-apk
        path: ./
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: app-debug.apk
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          🚀 **Automated APK Build**
          
          This release contains the latest APK build from commit ${{ github.sha }}
          
          **Installation:**
          1. Download the `app-debug.apk` file
          2. Enable "Install from unknown sources" on your Android device
          3. Install the APK file
          
          **Build Details:**
          - Commit: ${{ github.sha }}
          - Branch: ${{ github.ref_name }}
          - Build Number: ${{ github.run_number }}
          - Build Date: ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
